# Generated by bower2nix v3.1.1 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "angular" "1.5.8" "~1.5.0" "08xg1jych62bmcfsq3knfrqmqz7wsnb3jmbr6gk16rfp71vmrfw5")
  (fetchbower "bootstrap" "3.3.7" "~3.3.6" "0s36rlvbw73ibhzs807x9rjxgid133vxxqd85cr82cry6hz3nv91")
  (fetchbower "jquery" "3.1.1" "1.9.1 - 3" "1c8x5v9yjy96mqjpccqsd8zlwgws4nyy756rhdri1fzfp7xayh4n")
]; }
