# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "argparse-1.0.4" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.4.tgz";
        sha1 = "2b12247b933001971addcbfe4e67d20fd395bbf4";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "bower-1.8.14" = {
      name = "bower";
      packageName = "bower";
      version = "1.8.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower/-/bower-1.8.14.tgz";
        sha512 = "8Rq058FD91q9Nwthyhw0la9fzpBz0iwZTrt51LWl+w+PnJgZk9J+5wp3nibsJcIUPglMYXr4NRBaR+TUj0OkBQ==";
      };
    };
    "bower-endpoint-parser-0.2.1" = {
      name = "bower-endpoint-parser";
      packageName = "bower-endpoint-parser";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower-endpoint-parser/-/bower-endpoint-parser-0.2.1.tgz";
        sha1 = "8c4010a2900cdab07ea5d38f0bd03e9bbccef90f";
      };
    };
    "bower-json-0.8.4" = {
      name = "bower-json";
      packageName = "bower-json";
      version = "0.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower-json/-/bower-json-0.8.4.tgz";
        sha512 = "mMKghvq9ivbuzSsY5nrOLnDtZIJMUCpysqbGaGW3mj88JAcuSi8ZAzIt34vNZjohy0aR9VXLwgPTZGnBX2Vpjg==";
      };
    };
    "bower-logger-0.2.1" = {
      name = "bower-logger";
      packageName = "bower-logger";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower-logger/-/bower-logger-0.2.1.tgz";
        sha1 = "0c1817c48063a88d96cc3d516c55e57fff5d9ecb";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "deep-extend-0.5.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.5.1.tgz";
        sha512 = "N8vBdOa+DF7zkRrDCsaOXoCs/E2fJfx9B9MrKnnSiHNh4ws7eSys6YQE4KvT1cecKmOASYQBhbKjeuDD9lT81w==";
      };
    };
    "ends-with-0.2.0" = {
      name = "ends-with";
      packageName = "ends-with";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ends-with/-/ends-with-0.2.0.tgz";
        sha1 = "2f9da98d57a50cfda4571ce4339000500f4e6b8a";
      };
    };
    "ext-list-2.2.2" = {
      name = "ext-list";
      packageName = "ext-list";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext-list/-/ext-list-2.2.2.tgz";
        sha512 = "u+SQgsubraE6zItfVA0tBuCBhfU9ogSRnsvygI7wht9TS510oLkBRXBsqopeUG/GBOIQyKZO9wjTqIu/sf5zFA==";
      };
    };
    "fs-extra-0.26.7" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "0.26.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-0.26.7.tgz";
        sha1 = "9ae1fdd94897798edab76d0918cf42d0c3184fa9";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "intersect-1.0.1" = {
      name = "intersect";
      packageName = "intersect";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/intersect/-/intersect-1.0.1.tgz";
        sha1 = "332650e10854d8c0ac58c192bdc27a8bf7e7a30c";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "jsonfile-2.4.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz";
        sha1 = "3736a2b428b87bbda0cc83b53fa3d633a35c2ae8";
      };
    };
    "klaw-1.3.1" = {
      name = "klaw";
      packageName = "klaw";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-1.3.1.tgz";
        sha1 = "4088433b46b3b1ba259d78785d8e96f73ba02439";
      };
    };
    "lodash-4.2.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.2.1.tgz";
        sha1 = "171fdcfbbc30d689c544cd18c0529f56de6c1aa9";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "promised-temp-0.1.0" = {
      name = "promised-temp";
      packageName = "promised-temp";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promised-temp/-/promised-temp-0.1.0.tgz";
        sha1 = "5f8a704ccdf5f2ac23996fcafe2b301bc2a8d0eb";
      };
    };
    "q-1.5.1" = {
      name = "q";
      packageName = "q";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.1.tgz";
        sha1 = "7e32f75b41381291d04611f1bf14109ac00651d7";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "sort-keys-1.1.2" = {
      name = "sort-keys";
      packageName = "sort-keys";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys/-/sort-keys-1.1.2.tgz";
        sha1 = "441b6d4d346798f1b4e49e8920adfba0e543f9ad";
      };
    };
    "sort-keys-length-1.0.1" = {
      name = "sort-keys-length";
      packageName = "sort-keys-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys-length/-/sort-keys-length-1.0.1.tgz";
        sha1 = "9cb6f4f4e9e48155a6aa0671edd336ff1479a188";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "temp-0.8.3" = {
      name = "temp";
      packageName = "temp";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.8.3.tgz";
        sha1 = "e0c6bc4d26b903124410e4fed81103014dfc1f59";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
  args = {
    name = "bower2nix";
    packageName = "bower2nix";
    version = "3.3.0";
    src = ./.;
    dependencies = [
      sources."argparse-1.0.4"
      sources."balanced-match-1.0.2"
      sources."bower-1.8.14"
      sources."bower-endpoint-parser-0.2.1"
      sources."bower-json-0.8.4"
      sources."bower-logger-0.2.1"
      sources."brace-expansion-1.1.11"
      sources."concat-map-0.0.1"
      sources."debug-2.6.9"
      sources."deep-extend-0.5.1"
      sources."ends-with-0.2.0"
      sources."ext-list-2.2.2"
      sources."fs-extra-0.26.7"
      sources."fs.realpath-1.0.0"
      sources."glob-6.0.4"
      sources."graceful-fs-4.2.10"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."intersect-1.0.1"
      sources."is-plain-obj-1.1.0"
      sources."jsonfile-2.4.0"
      sources."klaw-1.3.1"
      sources."lodash-4.2.1"
      sources."mime-db-1.52.0"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.6"
      sources."mkdirp-0.5.6"
      sources."ms-2.0.0"
      sources."once-1.4.0"
      sources."os-tmpdir-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."promised-temp-0.1.0"
      sources."q-1.5.1"
      (sources."rimraf-2.7.1" // {
        dependencies = [
          sources."glob-7.2.0"
        ];
      })
      sources."semver-5.7.1"
      sources."sort-keys-1.1.2"
      sources."sort-keys-length-1.0.1"
      sources."sprintf-js-1.0.3"
      (sources."temp-0.8.3" // {
        dependencies = [
          sources."rimraf-2.2.8"
        ];
      })
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Generate nix expressions to fetch bower dependencies";
      homepage = "https://github.com/rvl/bower2nix";
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
